### PR TITLE
Changed the motor class to allow for all 5 motor types: PWM Talon; PWM V...

### PR DESCRIPTION
**Pull request by ghost**
...ictor; CAN Talon; CAN Jaguar; PWM Jaguar. Also added a function in the main robot class to allow for testing the plyboy lifting mechanism.

### CODE REVIEW

**Comment by georgetzavelas** [comment]
Hey Tylar,

Do a pull and resolve any conflicts, then I can merge your changes.

**Comment by ghost** [comment]
Ok so it should work now.

**Comment by georgetzavelas** [comment]
Did you do an amended commit?

GT

_From:_ D3ZOMBKEELA [mailto:notifications@github.com]
_Sent:_ February-03-15 6:45 PM
_To:_ FRC2994/FRC-2015
_Cc:_ George Tzavelas
_Subject:_ Re: [FRC-2015] Changed the motor class to allow for all 5 motor
types: PWM Talon; PWM V... (#12)

Ok so it should work now.

**Comment by ghost** [comment]
Amended commit?

**Comment by georgetzavelas** [comment]
I’ll show you tomorrow.

GT

_From:_ D3ZOMBKEELA [mailto:notifications@github.com]
_Sent:_ February-03-15 6:57 PM
_To:_ FRC2994/FRC-2015
_Cc:_ George Tzavelas
_Subject:_ Re: [FRC-2015] Changed the motor class to allow for all 5 motor
types: PWM Talon; PWM V... (#12)

Amended commit?

**Pull request closed without merging**
